ALTER TABLE OPPONENTS
ADD FOREIGN KEY (player1)
  REFERENCES PLAYER (id)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE OPPONENTS
ADD FOREIGN hibernate_sequenceKEY (player2)
  REFERENCES PLAYER (id)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
  
  ALTER TABLE PLAYER
ADD FOREIGN KEY (sponsorid)
  REFERENCES SPONSOR (id)
  ON DELETE CASCADE
  ON UPDATE CASCADE;